In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.3.4'

In [21]:
df = pd.read_csv('yellow_tripdata_2021-01.csv', nrows=100)

In [22]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2021-01-01 00:12:41,2021-01-01 00:26:47,1,4.13,1,N,161,226,1,14.5,0.5,0.5,3.66,0.0,0.3,21.96,2.5
96,2,2021-01-01 00:23:29,2021-01-01 00:35:03,2,4.12,1,N,162,74,2,13.5,0.5,0.5,0.00,0.0,0.3,17.30,2.5
97,2,2021-01-01 00:46:17,2021-01-01 00:54:25,2,2.22,1,N,144,170,1,9.0,0.5,0.5,2.56,0.0,0.3,15.36,2.5
98,2,2021-01-01 00:28:16,2021-01-01 00:51:44,1,7.11,1,N,264,264,2,23.5,0.5,0.5,0.00,0.0,0.3,24.80,0.0
99,2,2021-01-01 00:42:35,2021-01-01 00:54:41,3,1.61,1,N,229,237,2,9.5,0.5,0.5,0.00,0.0,0.3,13.30,2.5

In [23]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [24]:
from sqlalchemy import create_engine

In [36]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [37]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" FLOAT(53),
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	"RatecodeID" FLOAT(53),
	store_and_fwd_flag FLOAT(53),
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [38]:
df_iter = pd.read_csv('yellow_tripdata_2021-01.csv', iterator=True, chunksize=100000)

In [39]:
df = next(df_iter)

In [40]:
len(df)

100000

In [41]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [31]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-04 14:04:31,2021-01-04 14:08:52,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5
99996,1,2021-01-04 14:18:46,2021-01-04 14:35:45,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5
99997,1,2021-01-04 14:42:41,2021-01-04 14:59:22,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5
99998,2,2021-01-04 14:39:02,2021-01-04 15:09:37,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5
99999,2,2021-01-04 14:49:36,2021-01-04 14:54:44,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5

In [42]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

OperationalError: (psycopg2.OperationalError)
(Background on this error at: http://sqlalche.me/e/14/e3q8)

In [33]:
%time df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

Wall time: 10.3 s

In [34]:
from time import time

In [35]:
while True: 
    t_start = time()

    df = next(df_iter)

    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
    df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
    
    df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

    t_end = time()

    print('inserted another chunk, took %.3f second' % (t_end - t_start))

inserted another chunk, took 12.362 second
inserted another chunk, took 12.431 second
inserted another chunk, took 12.148 second
inserted another chunk, took 12.050 second
inserted another chunk, took 11.473 second
inserted another chunk, took 10.898 second
inserted another chunk, took 10.929 second
inserted another chunk, took 11.118 second
inserted another chunk, took 11.571 second
inserted another chunk, took 10.775 second
inserted another chunk, took 11.317 second

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3364: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

inserted another chunk, took 11.472 second
inserted another chunk, took 7.262 second

StopIteration:

In [35]:
!wget https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv

--2022-01-15 23:57:02--  https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.113.61
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.113.61|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: 'taxi+_zone_lookup.csv'

     0K .......... ..                                         100%  910K=0.01s

2022-01-15 23:57:02 (910 KB/s) - 'taxi+_zone_lookup.csv' saved [12322/12322]

In [36]:
df_zones = pd.read_csv('taxi+_zone_lookup.csv')

In [38]:
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [42]:
df_zones.to_sql(name='zones', con=engine, if_exists='replace')